env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules: {
         import/prefer-default-export: off,
         no-unused-vars: off,
         react/prop-types: off,
         react/jsx-props-no-spreading: off,
         no-nested-ternary: off,
         no-use-before-define: off,
         no-unused-expressions: off,
         react/destructuring-assignment: off,
         camelcase: warn,
         react/jsx-curly-newline: off,
         import/no-unresolved: off,
         react/require-default-props: off
}
