export const FETCH_WEATHER_CONDITIONS_START = 'FETCH_WEATHER_CONDITIONS_START';
export const FETCH_WEATHER_CONDITIONS_SUCCESS = 'FETCH_WEATHER_CONDITIONS_SUCCESS';
export const FETCH_WEATHER_CONDITIONS_FAILURE = 'FETCH_WEATHER_CONDITIONS_FAILURE';
export const FETCH_WEATHER_ALERTS_START = 'FETCH_WEATHER_ALERTS_START';
export const FETCH_WEATHER_ALERTS_SUCCESS = 'FETCH_WEATHER_ALERTS_SUCCESS';
export const FETCH_WEATHER_ALERTS_FAILURE = 'FETCH_WEATHER_ALERTS_FAILURE';
